name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ou a versão que você está usando
          cache: 'npm' # Adicionando cache de dependências

      - name: Install dependencies
        run: npm ci # Usa o package-lock.json para instalação consistente

      - name: Run ESLint
        run: npm run lint # Adicionando o passo de lint

      - name: Run Jest tests and collect coverage
        run: npm test # Isso agora gera a cobertura

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4 # Usando v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # directory: ./coverage/ # Opcional, se não for o padrão
          # flags: unittests # Opcional, para marcar os relatórios
          # fail_ci_if_error: true # Opcional, para falhar o CI se o upload falhar
        # Adicione um timeout para evitar que o job fique preso
        # https://github.com/codecov/codecov-action/issues/693
        timeout-minutes: 5 

      - name: Build project
        # Roda apenas se os passos anteriores (incluindo testes e upload de cobertura) foram bem-sucedidos
        if: success()
        run: npm run build

      - name: Run Cypress tests
        run: npm run test:e2e # Adicionando testes E2E

      - name: Deploy to Vercel
        # Roda apenas se os passos anteriores (incluindo testes E2E) foram bem-sucedidos
        if: success()
        uses: amondnet/vercel-action@v25 # Voltando para a v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Token de acesso Vercel
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # ID da sua organização Vercel
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # ID do seu projeto Vercel
          vercel-args: '--prod' # Argumentos para o comando Vercel (deploy de produção)

      # Adicionaremos o deploy do Vercel aqui depois que o build funcionar
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #     vercel-args: '--prod' 